// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat_proto.proto

package chatservice

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Aliasname            string   `protobuf:"bytes,1,opt,name=aliasname,proto3" json:"aliasname,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	HasRoom              bool     `protobuf:"varint,3,opt,name=hasRoom,proto3" json:"hasRoom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAliasname() string {
	if m != nil {
		return m.Aliasname
	}
	return ""
}

func (m *User) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *User) GetHasRoom() bool {
	if m != nil {
		return m.HasRoom
	}
	return false
}

type UserMessage struct {
	Aliasname            string   `protobuf:"bytes,1,opt,name=aliasname,proto3" json:"aliasname,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMessage) Reset()         { *m = UserMessage{} }
func (m *UserMessage) String() string { return proto.CompactTextString(m) }
func (*UserMessage) ProtoMessage()    {}
func (*UserMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{1}
}

func (m *UserMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMessage.Unmarshal(m, b)
}
func (m *UserMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMessage.Marshal(b, m, deterministic)
}
func (m *UserMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMessage.Merge(m, src)
}
func (m *UserMessage) XXX_Size() int {
	return xxx_messageInfo_UserMessage.Size(m)
}
func (m *UserMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMessage.DiscardUnknown(m)
}

var xxx_messageInfo_UserMessage proto.InternalMessageInfo

func (m *UserMessage) GetAliasname() string {
	if m != nil {
		return m.Aliasname
	}
	return ""
}

func (m *UserMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Room struct {
	RoomId               string         `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Messages             []*UserMessage `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Room) Reset()         { *m = Room{} }
func (m *Room) String() string { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()    {}
func (*Room) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{2}
}

func (m *Room) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Room.Unmarshal(m, b)
}
func (m *Room) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Room.Marshal(b, m, deterministic)
}
func (m *Room) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Room.Merge(m, src)
}
func (m *Room) XXX_Size() int {
	return xxx_messageInfo_Room.Size(m)
}
func (m *Room) XXX_DiscardUnknown() {
	xxx_messageInfo_Room.DiscardUnknown(m)
}

var xxx_messageInfo_Room proto.InternalMessageInfo

func (m *Room) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *Room) GetMessages() []*UserMessage {
	if m != nil {
		return m.Messages
	}
	return nil
}

type ContentMessage struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SenderId             string   `protobuf:"bytes,3,opt,name=senderId,proto3" json:"senderId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentMessage) Reset()         { *m = ContentMessage{} }
func (m *ContentMessage) String() string { return proto.CompactTextString(m) }
func (*ContentMessage) ProtoMessage()    {}
func (*ContentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{3}
}

func (m *ContentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentMessage.Unmarshal(m, b)
}
func (m *ContentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentMessage.Marshal(b, m, deterministic)
}
func (m *ContentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentMessage.Merge(m, src)
}
func (m *ContentMessage) XXX_Size() int {
	return xxx_messageInfo_ContentMessage.Size(m)
}
func (m *ContentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ContentMessage proto.InternalMessageInfo

func (m *ContentMessage) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *ContentMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ContentMessage) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

type LoginRequest struct {
	Request              *User    `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetRequest() *User {
	if m != nil {
		return m.Request
	}
	return nil
}

type LoginResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{5}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type RoomRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	AliasName            string   `protobuf:"bytes,2,opt,name=aliasName,proto3" json:"aliasName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomRequest) Reset()         { *m = RoomRequest{} }
func (m *RoomRequest) String() string { return proto.CompactTextString(m) }
func (*RoomRequest) ProtoMessage()    {}
func (*RoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{6}
}

func (m *RoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomRequest.Unmarshal(m, b)
}
func (m *RoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomRequest.Marshal(b, m, deterministic)
}
func (m *RoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomRequest.Merge(m, src)
}
func (m *RoomRequest) XXX_Size() int {
	return xxx_messageInfo_RoomRequest.Size(m)
}
func (m *RoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoomRequest proto.InternalMessageInfo

func (m *RoomRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *RoomRequest) GetAliasName() string {
	if m != nil {
		return m.AliasName
	}
	return ""
}

type RoomResponse struct {
	Response             *Room    `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomResponse) Reset()         { *m = RoomResponse{} }
func (m *RoomResponse) String() string { return proto.CompactTextString(m) }
func (*RoomResponse) ProtoMessage()    {}
func (*RoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{7}
}

func (m *RoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomResponse.Unmarshal(m, b)
}
func (m *RoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomResponse.Marshal(b, m, deterministic)
}
func (m *RoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomResponse.Merge(m, src)
}
func (m *RoomResponse) XXX_Size() int {
	return xxx_messageInfo_RoomResponse.Size(m)
}
func (m *RoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoomResponse proto.InternalMessageInfo

func (m *RoomResponse) GetResponse() *Room {
	if m != nil {
		return m.Response
	}
	return nil
}

type SendMessageRequest struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Senderalias          string   `protobuf:"bytes,2,opt,name=senderalias,proto3" json:"senderalias,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMessageRequest) Reset()         { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()    {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{8}
}

func (m *SendMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMessageRequest.Unmarshal(m, b)
}
func (m *SendMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMessageRequest.Marshal(b, m, deterministic)
}
func (m *SendMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMessageRequest.Merge(m, src)
}
func (m *SendMessageRequest) XXX_Size() int {
	return xxx_messageInfo_SendMessageRequest.Size(m)
}
func (m *SendMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMessageRequest proto.InternalMessageInfo

func (m *SendMessageRequest) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *SendMessageRequest) GetSenderalias() string {
	if m != nil {
		return m.Senderalias
	}
	return ""
}

func (m *SendMessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type StreamConnect struct {
	Senderalias          string   `protobuf:"bytes,1,opt,name=senderalias,proto3" json:"senderalias,omitempty"`
	RoomId               string   `protobuf:"bytes,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamConnect) Reset()         { *m = StreamConnect{} }
func (m *StreamConnect) String() string { return proto.CompactTextString(m) }
func (*StreamConnect) ProtoMessage()    {}
func (*StreamConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{9}
}

func (m *StreamConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamConnect.Unmarshal(m, b)
}
func (m *StreamConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamConnect.Marshal(b, m, deterministic)
}
func (m *StreamConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamConnect.Merge(m, src)
}
func (m *StreamConnect) XXX_Size() int {
	return xxx_messageInfo_StreamConnect.Size(m)
}
func (m *StreamConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamConnect.DiscardUnknown(m)
}

var xxx_messageInfo_StreamConnect proto.InternalMessageInfo

func (m *StreamConnect) GetSenderalias() string {
	if m != nil {
		return m.Senderalias
	}
	return ""
}

func (m *StreamConnect) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *StreamConnect) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_b83b92118989af34, []int{10}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*User)(nil), "chatservice.User")
	proto.RegisterType((*UserMessage)(nil), "chatservice.UserMessage")
	proto.RegisterType((*Room)(nil), "chatservice.Room")
	proto.RegisterType((*ContentMessage)(nil), "chatservice.ContentMessage")
	proto.RegisterType((*LoginRequest)(nil), "chatservice.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "chatservice.LoginResponse")
	proto.RegisterType((*RoomRequest)(nil), "chatservice.RoomRequest")
	proto.RegisterType((*RoomResponse)(nil), "chatservice.RoomResponse")
	proto.RegisterType((*SendMessageRequest)(nil), "chatservice.SendMessageRequest")
	proto.RegisterType((*StreamConnect)(nil), "chatservice.StreamConnect")
	proto.RegisterType((*Empty)(nil), "chatservice.Empty")
}

func init() { proto.RegisterFile("chat_proto.proto", fileDescriptor_b83b92118989af34) }

var fileDescriptor_b83b92118989af34 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x55, 0xda, 0xa5, 0x69, 0x27, 0x5d, 0x04, 0x46, 0x5a, 0x79, 0x03, 0x87, 0xca, 0xa7, 0x22,
	0x44, 0x85, 0x0a, 0x27, 0x10, 0x5c, 0xa2, 0x3d, 0x14, 0x2d, 0x20, 0xa5, 0xc0, 0x11, 0x64, 0xd2,
	0x51, 0x1b, 0x69, 0x63, 0x17, 0xdb, 0xbb, 0x12, 0x9f, 0xc5, 0x1f, 0xa2, 0x38, 0x76, 0xd7, 0xa6,
	0xed, 0xee, 0xa5, 0xca, 0xcc, 0xbc, 0xbc, 0x79, 0xf3, 0x66, 0x52, 0x78, 0x54, 0x6d, 0xb8, 0xf9,
	0xb9, 0x55, 0xd2, 0xc8, 0x99, 0xfd, 0x25, 0x59, 0x9b, 0xd1, 0xa8, 0x6e, 0xea, 0x0a, 0xd9, 0x77,
	0x38, 0xf9, 0xa6, 0x51, 0x91, 0x67, 0x30, 0xe2, 0x57, 0x35, 0xd7, 0x82, 0x37, 0x48, 0x93, 0x49,
	0x32, 0x1d, 0x95, 0xb7, 0x09, 0x72, 0x06, 0x03, 0x25, 0x65, 0xb3, 0x58, 0xd1, 0x9e, 0x2d, 0xb9,
	0x88, 0x50, 0x48, 0x37, 0x5c, 0x97, 0x52, 0x36, 0xb4, 0x3f, 0x49, 0xa6, 0xc3, 0xd2, 0x87, 0xec,
	0x02, 0xb2, 0x96, 0xf7, 0x13, 0x6a, 0xcd, 0xd7, 0x78, 0x0f, 0x3d, 0x85, 0xb4, 0xe9, 0x80, 0x8e,
	0xdf, 0x87, 0xec, 0x2b, 0x9c, 0xb4, 0x74, 0x81, 0x80, 0x24, 0x12, 0xf0, 0x06, 0x86, 0x0e, 0xaa,
	0x69, 0x6f, 0xd2, 0x9f, 0x66, 0x73, 0x3a, 0x0b, 0xc6, 0x9b, 0x05, 0x1a, 0xca, 0x1d, 0x92, 0xfd,
	0x80, 0x87, 0x85, 0x14, 0x06, 0x85, 0xf1, 0xfa, 0x8e, 0xf1, 0x53, 0x48, 0xab, 0x0e, 0xe9, 0x95,
	0xb9, 0x90, 0xe4, 0x30, 0xd4, 0x28, 0x56, 0xa8, 0x16, 0x2b, 0x3b, 0xfb, 0xa8, 0xdc, 0xc5, 0xec,
	0x1d, 0x8c, 0x2f, 0xe5, 0xba, 0x16, 0x25, 0xfe, 0xbe, 0x46, 0x6d, 0xc8, 0x0b, 0x48, 0x55, 0xf7,
	0x68, 0xe9, 0xb3, 0xf9, 0xe3, 0x3d, 0x91, 0xa5, 0x47, 0xb0, 0xb7, 0x70, 0xea, 0x5e, 0xd6, 0x5b,
	0x29, 0x34, 0x92, 0xe7, 0x30, 0x50, 0xa8, 0xaf, 0xaf, 0xee, 0x78, 0xd9, 0x01, 0x58, 0x01, 0x59,
	0x6b, 0x97, 0xef, 0x7b, 0x6c, 0x2a, 0xbf, 0x8d, 0xcf, 0xed, 0x36, 0x7a, 0xc1, 0x36, 0xda, 0x04,
	0x7b, 0x0f, 0xe3, 0x8e, 0xc4, 0xf5, 0x7f, 0x09, 0x43, 0xe5, 0x9e, 0x0f, 0x2a, 0xb0, 0xe0, 0x1d,
	0x84, 0x6d, 0x80, 0x2c, 0x51, 0xac, 0xbc, 0xeb, 0xf7, 0x48, 0x99, 0x40, 0xd6, 0xd9, 0x66, 0xfb,
	0x3b, 0x31, 0x61, 0x2a, 0x3c, 0x8e, 0x7e, 0x7c, 0x1c, 0x1c, 0x4e, 0x97, 0x46, 0x21, 0x6f, 0x0a,
	0x29, 0x04, 0x56, 0xe6, 0x7f, 0xb2, 0x64, 0x9f, 0xec, 0xd8, 0x21, 0x9f, 0xc1, 0x80, 0x57, 0xa6,
	0xbe, 0x41, 0x77, 0xc7, 0x2e, 0x62, 0x29, 0x3c, 0xb8, 0x68, 0xb6, 0xe6, 0xcf, 0xfc, 0x6f, 0x0f,
	0xb2, 0x62, 0xc3, 0xcd, 0xb2, 0x1b, 0x9a, 0x5c, 0xc2, 0x93, 0x12, 0xd7, 0xb5, 0x36, 0xa8, 0xbe,
	0x28, 0xbb, 0x2f, 0xfb, 0x19, 0x9d, 0x47, 0xce, 0x84, 0x47, 0x90, 0xe7, 0x87, 0x4a, 0xce, 0xe2,
	0x05, 0x90, 0x5b, 0xb6, 0x8f, 0xb2, 0x16, 0xf6, 0xe8, 0xe9, 0xbe, 0xcd, 0x8e, 0xeb, 0xfc, 0x40,
	0x65, 0x47, 0x35, 0x2e, 0x14, 0x72, 0x83, 0x9d, 0x35, 0x24, 0x6e, 0x1b, 0xf9, 0x95, 0x3f, 0x8d,
	0x6a, 0xf1, 0x27, 0xf1, 0x2a, 0x21, 0x1f, 0x20, 0x0b, 0x36, 0x49, 0xee, 0x42, 0xe7, 0x24, 0x2a,
	0x5a, 0xcf, 0x7e, 0x0d, 0xec, 0xff, 0xcd, 0xeb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa5, 0xcd,
	0x5b, 0xe4, 0x83, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	RegisterOrLoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	RegisterOrJoinRoom(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*RoomResponse, error)
	CreateStream(ctx context.Context, in *StreamConnect, opts ...grpc.CallOption) (ChatService_CreateStreamClient, error)
	SendMessage(ctx context.Context, in *ContentMessage, opts ...grpc.CallOption) (*Empty, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) RegisterOrLoginUser(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/chatservice.ChatService/RegisterOrLoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) RegisterOrJoinRoom(ctx context.Context, in *RoomRequest, opts ...grpc.CallOption) (*RoomResponse, error) {
	out := new(RoomResponse)
	err := c.cc.Invoke(ctx, "/chatservice.ChatService/RegisterOrJoinRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateStream(ctx context.Context, in *StreamConnect, opts ...grpc.CallOption) (ChatService_CreateStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/chatservice.ChatService/CreateStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceCreateStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatService_CreateStreamClient interface {
	Recv() (*ContentMessage, error)
	grpc.ClientStream
}

type chatServiceCreateStreamClient struct {
	grpc.ClientStream
}

func (x *chatServiceCreateStreamClient) Recv() (*ContentMessage, error) {
	m := new(ContentMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *ContentMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/chatservice.ChatService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	RegisterOrLoginUser(context.Context, *LoginRequest) (*LoginResponse, error)
	RegisterOrJoinRoom(context.Context, *RoomRequest) (*RoomResponse, error)
	CreateStream(*StreamConnect, ChatService_CreateStreamServer) error
	SendMessage(context.Context, *ContentMessage) (*Empty, error)
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) RegisterOrLoginUser(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterOrLoginUser not implemented")
}
func (*UnimplementedChatServiceServer) RegisterOrJoinRoom(ctx context.Context, req *RoomRequest) (*RoomResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterOrJoinRoom not implemented")
}
func (*UnimplementedChatServiceServer) CreateStream(req *StreamConnect, srv ChatService_CreateStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateStream not implemented")
}
func (*UnimplementedChatServiceServer) SendMessage(ctx context.Context, req *ContentMessage) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_RegisterOrLoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).RegisterOrLoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.ChatService/RegisterOrLoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).RegisterOrLoginUser(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_RegisterOrJoinRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).RegisterOrJoinRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.ChatService/RegisterOrJoinRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).RegisterOrJoinRoom(ctx, req.(*RoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConnect)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatServiceServer).CreateStream(m, &chatServiceCreateStreamServer{stream})
}

type ChatService_CreateStreamServer interface {
	Send(*ContentMessage) error
	grpc.ServerStream
}

type chatServiceCreateStreamServer struct {
	grpc.ServerStream
}

func (x *chatServiceCreateStreamServer) Send(m *ContentMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContentMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatservice.ChatService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*ContentMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chatservice.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterOrLoginUser",
			Handler:    _ChatService_RegisterOrLoginUser_Handler,
		},
		{
			MethodName: "RegisterOrJoinRoom",
			Handler:    _ChatService_RegisterOrJoinRoom_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateStream",
			Handler:       _ChatService_CreateStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chat_proto.proto",
}
